twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:  ['bootstrap_4_horizontal_layout.html.twig']

    globals:
        navigation:
            home:
                href:
                    'home'
                caption:
                    'Home'
            reservations:
                href:
                    'reservations'
                caption:
                    'Reservations'
            orders:
                href:
                    'orders'
                caption:
                    'Orders'
            rooms:
                href:
                    'room'
                caption:
                    'Rooms'